# Meta Data for SEO

## Homepage
title = "Altair"
titleSeparator = "-"
titleAddition = "Distributed API Gateway"
description = "Altair is an open source API gateway written in Go. Designed to be distributed, lightweight, simple, fast, reliable, cross platform, programming language agnostic and robust - by default"

## Open Graph + Twitter Cards
images = ["altair.png"]
twitterSite = "insomnius_"
twitterCreator = "insomnius_"
facebookAuthor = "insomnius.arief"
facebookPublisher = "insomnius.arief"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/insomnius_"
schemaLinkedIn = "https://www.linkedin.com/in/insomnius/"
schemaGitHub = "https://github.com/codefluence-x"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by Codefluence"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false
